timezone: America/New_York
exclude: [node_modules, vendor, Gemfile, Gemfile.lock, Makefile, package.json, yarn.lock]
permalink: /blog/:year/:month/:day/:title.html

sass:
  load_paths:
    - _sass
    - node_modules

collections:
  portfolio:
    output: true

analytics: GTM-XXXXXXX