[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"
    cache-control = "public,max-age=60"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    Referrer-Policy = "no-referrer-when-downgrade"
    Report-To = '''{
      "group":"default",
      "max_age":31536000,
      "endpoints":[
        {"url":"https://andrewpucci.report-uri.com/a/d/g"}
      ],
      "include_subdomains":true}'''
    NEL = '''{
      "report_to":"default",
      "max_age":31536000,
      "include_subdomains":true
    }'''

[[headers]]
  for = "/*.*"
  [headers.values]
  cache-control = "public,max-age=360000"

[[redirects]]
  from = "/shotplot"
  to = "https://shotplot.app"
  status = 301
  force = true

[[plugins]]
package = "netlify-plugin-csp-generator"

  [plugins.inputs]
  buildDir = "dist"
  reportURI = "https://andrewpucci.report-uri.com/r/d/csp/enforce"

  [plugins.inputs.policies]
    defaultSrc = "'none'"
    scriptSrc = "'self'"
    styleSrc = "'self' 'unsafe-hashes'"
    imgSrc = "'self' data:"
    fontSrc = "'self'"
    connectSrc = "'none'"
    mediaSrc = "'none'"
    objectSrc = "'none'"
    prefetchSrc = "'self'"
    frameSrc = "'none'"
    workerSrc = "'none'"
    frameAncestors = "'none'"
    formAction = "'none'"
    baseUri = "'self'"
    manifestSrc = "'none'"
