version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.15.1
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Run Project Build
          command: yarn prod
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Run Tests
          command: yarn test
      - persist_to_workspace:
          root: ~/project/workspace
          paths:
            - dist
  deploy:
    docker:
      - image: circleci/node:8.15.1
    steps:
      - attach_workspace:
          at: ~/project/workspace
      - add_ssh_keys:
          fingerprints:
            - "38:ad:a6:e9:f5:1e:71:4b:73:4a:47:e5:3b:96:04:5a"
      - run:
          name: Deploy Over SSH
          working_directory: ~/project
          command: |
            echo '$SSH_SERVER ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBPSw5DFWu8CHrcKtsnJgVcyriLsLHIut059MrPiG7KA31roUxslihvnUnVsZNl5XAQlVWdz5gwnSbkU9QTsNq+c=' >> ~/.ssh/known_hosts
            scp -r ~/project/workspace/dist/* $SSH_USER@$SSH_SERVER:$SSH_DIR
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
