version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.15.1
    working_directory: ~/project
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Run Project Build
          command: yarn prod
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Run Tests
          command: yarn test
  deploy:
    docker:
      - image: circleci/node:8.15.1
    working_directory: ~/project
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "38:ad:a6:e9:f5:1e:71:4b:73:4a:47:e5:3b:96:04:5a"
      - run:
          name: Deploy Over SSH
          working_directory: ~/project
          command: |
            yarn prod
            for ip in $(dig @1.1.1.1 $SSH_SERVER +short); do ssh-keyscan $SSH_SERVER,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts
            scp -r ~/project/dist/* $SSH_USER@$SSH_SERVER:$SSH_DIR
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
