version: 2
jobs:
  build:
    docker:
      - image: circleci/node:dubnium
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Build Project
          command: yarn prod
      - run:
          name: Run Tests
          command: yarn test
      - persist_to_workspace:
          root: ~/project
          paths:
            - dist
  deploy:
    docker:
      - image: circleci/node:8.15.1
    steps:
      - attach_workspace:
          at: ~/project
      - add_ssh_keys
      - run:
          name: Deploy Over SSH
          working_directory: ~/project
          command: |
            echo $SSH_KNOWN_HOSTS >> ~/.ssh/known_hosts
            sudo apt install rsync
            rsync -acv --delete --filter='P .*' ./dist/ $SSH_USER@$SSH_SERVER:$SSH_DIR

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
